version: '3.8'  # Use Docker Compose file format version 3.8

services:
  frontend:
    image: node:14-alpine  # Use Node.js image with Alpine Linux
    container_name: frontend-container  # Name of the frontend container
    ports:
      - "3000:3000"  # Map container port 3000 to host port 3000
    volumes:
      - ./frontend:/app  # Mount local directory to frontend application directory inside the container
    environment:
      - NODE_ENV=production  # Set Node.js environment to production
    command: npm start  # Command to start your frontend application
